# Generated by Django 3.2.3 on 2021-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addnurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nurse_name', models.CharField(default='', max_length=50)),
                ('Nurse_specialist', models.CharField(choices=[('select', 'select'), ('Dentist', 'Dentist'), ('Homeyopethic', 'Homeyopethic'), ('Orthopedic', 'Orthopedic')], default='', max_length=20)),
                ('Nurse_email', models.EmailField(default='', max_length=100)),
                ('Nurse_number', models.PositiveBigIntegerField(default='+91')),
                ('Nurse_expirence', models.CharField(default='', max_length=10)),
                ('Nurse_password', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
