# Generated by Django 3.2.3 on 2021-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Number', models.PositiveBigIntegerField(default='+91')),
                ('Password', models.CharField(default='', max_length=12)),
                ('Confirm_password', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
