# Generated by Django 3.2.3 on 2021-08-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_usersearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearch',
            old_name='spacialist',
            new_name='Spacialist',
        ),
    ]
