# Generated by Django 3.2.3 on 2021-08-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_spacialist_usersearch_spacialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnurse',
            name='Nurse_fees',
            field=models.CharField(default='', max_length=20),
        ),
    ]
