# Generated by Django 3.2.3 on 2021-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_addnurse_nurse_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnurse',
            name='Nurse_expirence',
            field=models.CharField(default='', max_length=25),
        ),
    ]
