# Generated by Django 3.2.3 on 2021-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_addnurse_nurse_expirence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booknurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(default='', max_length=50)),
                ('Book_specialist', models.CharField(choices=[('select', 'select'), ('Dentist', 'Dentist'), ('Homeyopethic', 'Homeyopethic'), ('Orthopedic', 'Orthopedic')], default='', max_length=20)),
                ('Book_email', models.EmailField(default='', max_length=100)),
                ('Book_expirence', models.CharField(default='', max_length=20)),
                ('Book_fees', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
