# Generated by Django 3.2.3 on 2021-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_nurseshedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseshedule',
            name='End_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='nurseshedule',
            name='Start_time',
            field=models.TimeField(),
        ),
    ]
