# Generated by Django 3.2.3 on 2021-08-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20210827_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseshedule',
            name='End_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nurseshedule',
            name='Start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
