# Generated by Django 3.2.3 on 2021-08-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20210827_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseshedule',
            name='End_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nurseshedule',
            name='Start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
