# Generated by Django 3.2.3 on 2021-08-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20210827_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersearch',
        ),
    ]
