# Generated by Django 3.2.3 on 2021-08-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_remove_nurseshedule_specialist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurseshedule',
        ),
    ]
