# Generated by Django 3.2.3 on 2021-08-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_rename_name_nurseshedule_aname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseshedule',
            old_name='AName',
            new_name='Name',
        ),
    ]
