# Generated by Django 3.2.3 on 2021-08-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_alter_nurseshedule_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurseshedule',
        ),
    ]
