# Generated by Django 3.2.3 on 2021-08-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_auto_20210831_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(default='', max_length=50)),
                ('Message', models.CharField(default='', max_length=1000)),
                ('joinuser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.addnurse')),
            ],
        ),
        migrations.DeleteModel(
            name='Booknurse',
        ),
    ]
