# Generated by Django 3.2.3 on 2021-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_auto_20210831_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cn_Expirence',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='Cn_fees',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='Cn_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
