# Generated by Django 3.2.3 on 2021-08-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0029_auto_20210831_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cn_Email',
            field=models.EmailField(default='', max_length=60),
        ),
    ]
