# Generated by Django 3.2.3 on 2021-08-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_cart_cn_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cn_specialist',
            field=models.CharField(default='', max_length=20),
        ),
    ]
