# Generated by Django 3.2.3 on 2021-09-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0031_cart_cn_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cn_Email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cn_Expirence',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cn_fees',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cn_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cn_specialist',
        ),
        migrations.AddField(
            model_name='cart',
            name='joinNurse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.addnurse'),
        ),
        migrations.AddField(
            model_name='cart',
            name='joinshedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.setshedule'),
        ),
    ]
