# Generated by Django 3.2.3 on 2021-09-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_auto_20210901_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='joinshedule',
        ),
    ]
