# Generated by Django 3.2.3 on 2021-09-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0033_remove_cart_joinshedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='joinNurse',
        ),
    ]
