# Generated by Django 3.2.3 on 2021-09-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0036_auto_20210901_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setshedule',
            new_name='Setshedule1',
        ),
    ]
