# Generated by Django 3.2.3 on 2021-09-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0037_rename_setshedule_setshedule1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setshedule1',
            new_name='Nurseshedule',
        ),
    ]
