# Generated by Django 3.2.3 on 2021-09-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0039_auto_20210901_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurseshedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('root', models.CharField(choices=[('select', 'select'), ('Morning', 'Morning'), ('Afternoot', 'Afternoot'), ('Evning', 'Evning')], default='', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('join_N', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.addnurse')),
            ],
        ),
        migrations.DeleteModel(
            name='Setshedule',
        ),
    ]
