# Generated by Django 3.2.3 on 2021-09-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0040_auto_20210901_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurseshedule',
        ),
    ]
