# Generated by Django 3.2.3 on 2021-09-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0045_cart_joinshedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='joinshedule',
        ),
    ]
