# Generated by Django 3.2.3 on 2021-09-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0046_remove_cart_joinshedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='joinshedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.setshedule'),
        ),
    ]
